const patientNode = {
  "Individual Unique ID": "pid",
  Name: "name",
  "ID Proof Type": "idprftype",
  "ID Proof Number": "idprfno",
  "Number of family members": "no_fm",
  Status: "sts",
  Gender: "gndr",
  "Contact number": "ctc_no",
  "Marital Status": "ms",
  "Father's Name": "f_name",
  "Mother's Name": "m_name",
  Age: "age",
  "Weight (in kgs)": "wt",
  "Height (in cms)": "ht",
  Religion: "rlg",
  Education: "edu",
  "Occupation Group - According to NCO 2015": "occgrp",
  "Estimated Annual Family Income": "fam_inc",
};
const form_1Node = {
  "Have you heard about cancer ?": "abt_ca",
  "Are you aware of the symptoms/warning signs of cancer?": "ws_ca",
  "Do you think tobacco causes cancer?": "tcc",
  "Can cancer spread from one person to another?": "spp",
  "Is there treatment and cure for cancer?": "tmt_cc",
  "Exposure to second hand smoke": "shsm",
  "Do you currently use tobacco in any form?": "tif",
  'If answered "yes" or "not now", for how many years have you had the habit? ': "yoh",
  "If not now, how long has it been since you quit the habit? ": "qth",
  "Types of tobacco consumption": "ttc",
  "Frequency of use / day [Smoked tobacco - beedi, cigarettes]": "ttc_val:stbc",
  "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]": "ttc_val:stghpms",
  "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]": "ttc_val:bqt",
  "Frequency of use / day [Betel quid without tobacco]": "ttc_val:bqwot",
  "Frequency of use / day [Others ]": "ttc_val:othr",
  "Have you attempted to quit tobacco in the past ?": "aqtp",
  "If yes, what was the method you adopted? ": "mthd", 
  "For how many days did you quit the habit? ": "hdqh", 
  "What was the reason to quit the habit?": "rtqh",
  "Alcohol consumption status": "acs",
  "If yes, since when": "acsw",
  "If not now, how long has it been since you quit ": "hlqh",
  "For how long did you consume alcohol?": "hlca",
  "Alcohol consumption frequency": "acf",
  "Have you undergone any cancer screening tests before?": "uacstb",
  "If yes, when? ": "wcswd",
  "Which cancer were you screened for?": "csf",
  "What was the reason for screening?": "rcs",
  "Was any blood related family member diagnosed with cancer?": "fmca",
  "Warning signs of cancer - if any of the following complaints are present / persistent, please tick all the options that apply to you": "wsoc",
  "Female specific symptoms": "fss",
  "Menstruation stage": "ms",
  "Age of menarche": "age_me",
  "Last menstrual period": "lmp",
  Menstruation: "mens",
  "Reason for hysterectomy": "hystrtmy_rsn",
  "Age at hysterectomy": "aah",
  "Age at menopause": "age_m",
  Gravida: "gvd",
  Para: "para",
  Living: "lvng",
  Abortion: "abrt",
  "Age at first child": "afc",
  "1st Child": "bfh:ch1",
  "2nd Child": "bfh:ch2",
  "3rd Child": "bfh:ch3",
  "4th Child": "bfh:ch4",
  "5th Child": "bfh:ch5",
  "6th Child": "bfh:ch6",
  "Hypertension present": "ht_p",
  "K/C/O HTN": "k_c_o:htval",
  "Diabetes present": "dia_p",
  "K/C/O DM": "k_c_o:dval",
  "Cancer present": "ca_p",
  "K/C/O Cancer": "k_c_o:cval",
};
const mvd = {
  "Heart Rate": "hr",
  SPO2: "spo",
  "BP/SBP": "bp",
  "BP/DBP": "bp",
  GRBS: "grbs",
  "Total Body Fat": "tbf",
  "Subcutaneous Body Fat": "sbf",
  "Visceral Body Fat": "vbf",
  "Waist Circumference(in cm)": "wc",
  "Hip Circumference(in cm)": "hc",
};
const form3 = {
  "Screening done for": "scr_dne_for",
  Findings: "fndgs",
  "Oral cavity Photos": "gpa",
  "Homogenous leukoplakia": "hl",
  "Homogenous leukoplakia - Lesion dimension": "hl",
  "Non homogenous leukoplakia": "nhl",
  "Non homogenous leukoplakia - Lesion dimension": "nhl",
  Erythroleukoplakia: "elp",
  "Erythroleukoplakia - Lesion dimension": "elp",
  Erythroplakia: "ep",
  "Erythroplakia - Lesion dimension": "ep",
  OSMF: "osmf",
  "Lichen planus present": "lpp",
  "Lichen planus present - Lesion location": "lpp",
  "Suspicious ulcer present": "sugrwth",
  "Suspicious ulcer present - Lesion size": "sugrwth",
  "Suspicious growth": "sus_grwth",
  "Suspicious growth present - Lesion size": "sus_grwth",
  "Smokers Palate": "smkrspalate",
  "Oral punch biopsy indicated": "pnchbi",
  "Laser procedure advised": "lpa",
  "Breast Examination Right breast": "brst_exm/r_b",
  "Breast Examination Left breast": "brst_exm/l_b",
  "Abnormality location Right breast": "abn_det/abn_rb",
  "Abnormality location Left breast": "abn_det/abn_lb",
  "Breast Photos": "bpa",
  "Nipple discharge": "nd",
  "Advised bilateral screening mammography": "adv_mgphy",
  "Advised bilateral screening ultrasound": "adv_mgphy",
  "FNAC done when indicated": "fnac_dn_in",
  "Nipple discharge smear taken when indicated": "ndstwi",
  Information: "infrmn",
  "Per Speculum": "perspec",
  VIA: "via",
  "Releveant images": "cpa",
  "Pap smear taken": "trtpap",
  "Cervical Punch biopsy indicated": "pbti",
  Recommendation: "recdn/recmd",
};
const Tcc = {
  "Amount spent on tobacco per day": "ad",
  "Types of tobacco consumption": "type_tc",
  "Frequency of use / day [Smoked tobacco - beedi, cigarettes]": "ae/smoked_tobacco_beedi_cigarettes",
  "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]": "ae/smokeless_tobacco_ghutka_hans_pan_masala_snuff",
  "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]": "ae/betel_quid_with_tobacco",
  "Frequency of use / day [Betel quid without tobacco]": "ae/betel_quid_without_tobacco",
  "Frequency of use / day [Others ]": "ae/other",
  "For how many years have you had the habit?": "yh",
  "Family history of Tobacco use": "ag/tu",
  "Family history of Substance use": "ag/su",
  "Family history of Mental disorder use": "ag/md",
  "Age of uptake": "age",
  "Reason for uptake / Starting the habit": "ba",
  "I smoke to keep myself alert": "ca",
  "Smoking is pleasant and relaxing": "cb",
  "I smoke when I am upset about something": "cc",
  "I smoke out of boredom": "cd",
  "If I run out of cigarette/beedi, I find it unbearable.": "ce",
  "I smoke automatically without being aware of it.": "cf",
  "I smoke to perk myself up.": "cg",
  "I find it difficult to go about my job without smoking": "ch",
  "I need to smoke in order to pass motion.": "ci",
  "I get real cravings for cigarette/beedi when I haven't used in a while": "cj",
  "I use it to keep from slowing down": "ea",
  "I like the texture and taste of it in my mouth.": "eb",
  "I find it pleasant and relaxing": "ec",
  "I use it when I am upset about something": "ed",
  "I chew it out of boredom.": "ee",
  "If I run out of it, I find it unbearable.": "ef",
  "I believe that it provides calcium.": "eg",
  "I use it to perk myself up.": "eh",
  "It relieves pain in my jaw/teeth.": "ei",
  "I find it difficult to go about with my job without it.": "ej",
  "Fagerstorm Test for Nicotine Dependence - How soon after you wake up do you smoke your first cigarette?": "da",
  "Fagerstorm Test for Nicotine Dependence - Do you find it difficult to refrain from smoking in places where it is forbidden, e.g., temples, during an outing with family, during village festivities?":
    "db",
  "Fagerstorm Test for Nicotine Dependence - Which cigarette would you hate most to give up?": "dc",
  "Fagerstorm Test for Nicotine Dependence - How many cigarettes per day do you smoke?": "dd",
  "Fagerstorm Test for Nicotine Dependence - Do you smoke more frequently during the first hours of waking than during the rest of the day?": "de",
  "Fagerstorm Test for Nicotine Dependence - Do you smoke even if you are sick in bed?": "df",
  "Modified Fagerstorm Test - How soon after you wake up do you place your first dip?": "fa",
  "Modified Fagerstorm Test - How often do you intentionally swallow its juice?": "fb",
  "Modified Fagerstorm Test - Which chew would you hate most to give up?": "fc",
  "Modified Fagerstorm Test - How many cans/pouches per week do you use?": "fd",
  "Modified Fagerstorm Test - Do you chew more frequently during the first hours after waking than during the rest of the day?": "fe",
  "Modified Fagerstorm Test - Do you chew even if you are sick in the bed?": "ff",
  "Do you intend to quit the habit": "fg",
  "Have you previously attempted to quit the habit?": "fh",
  "what among the following were the barriers to quit?": "fi",
  "Do you often forget the intention behind quitting?": "fj",
  "Did you have the right social support?": "fk",
  "Are you fearful of what might happen if you quit?": "fl",
  "Are you anticipating sadness when you quit?": "fm",
  "Do you find yourself thinking about death?": "fo",
  "Do you wish to live a healthy life?": "fp",
  "Do you believe that using tobacco is healthy?": "fq",
  "Does anyone in the family believe your habits are unhealthy?": "fr",
  "Would you agree if someone told you that use of tobacco in any form is not healthy?": "fs",
  "Are you thinking of quitting the habit now?": "ft",
  "Do you think that quitting takes a lot of effort?": "ga",
  "Do your family support you in quitting the habit?": "gb",
  "Do your friends support you in quitting the habit?": "gc",
  "Would you be willing to quit if someone from the family puts in the same effort to help?": "gd",
  "Would it be helpful if the counsellor gave you a nudge every now and then?": "ge",
  "Would you need some time to think whether you want to quit or not?": "gf",
  "Do you believe you are capable of quitting?": "gg",
  "Do you believe you can quit on your own?": "gh",
  "If there were professionals to help you out would you make an effort to quit?": "gi",
  "Which form of professional intervention would you prefer ?": "gj",
  "Which mode of therapy would you prefer?": "gk",
  "Dependency score for smoke tobacco": "ha",
  "Dependency level for smoke tobacco": "hb",
  "Dependency score for chewing habits": "hc",
  "Dependency level for smokeless tobacco": "hd",
  "Motivation stage assessed": "he",
  "Counselling Techniques": "hh",
};

export { patientNode, form_1Node, mvd, form3, Tcc };
