/**
 *  Generates an array of strings representing numbers from start to end, inclusive.
 * @param {number} start
 * @param {number} end
 * @returns {string[]} Returns an array of strings representing numbers from start to end, inclusive.
 */
function numberStrings(start, end) {
  return Array.from({ length: end - start + 1 }, (_, i) => (start + i).toString());
}

const data = [
  {
    id: 1,
    msg: "Survey",
    fields: [
      "ID Proof Type",
      "Number of family members",
      "Status",
      "Gender",
      "Marital Status",
      "Age",
      "Weight (in kgs)",
      "Height (in cms)",
      "Religion",
      "Education",
      "Occupation Group - According to NCO 2015",
      "Estimated Annual Family Income",
      "Have you heard about cancer ?",
      "Are you aware of the symptoms/warning signs of cancer?",
      "Do you think tobacco causes cancer?",
      "Can cancer spread from one person to another?",
      "Is there treatment and cure for cancer?",
      "Exposure to second hand smoke",
      "Do you currently use tobacco in any form?",
      'If answered "yes" or "not now", for how many years have you had the habit? ',
      "If not now, how long has it been since you quit the habit? ",
      "Types of tobacco consumption",
      "Frequency of use / day [Smoked tobacco - beedi, cigarettes]",
      "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]",
      "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]",
      "Frequency of use / day [Betel quid without tobacco]",
      "Frequency of use / day [Others ]",
      "Have you attempted to quit tobacco in the past ?",
      "If yes, what was the method you adopted? ",
      "For how many days did you quit the habit? ",
      "What was the reason to quit the habit?",
      "Alcohol consumption status",
      "If yes, since when",
      "If not now, how long has it been since you quit ",
      "For how long did you consume alcohol?",
      "Alcohol consumption frequency",
      "Have you undergone any cancer screening tests before?",
      "If yes, when? ",
      "Which cancer were you screened for?",
      "What was the reason for screening?",
      "Was any blood related family member diagnosed with cancer?",
      "If yes, how many? ",
      "Warning signs of cancer - if any of the following complaints are present / persistent, please tick all the options that apply to you",
      "Female specific symptoms",
      "Menstruation stage",
      "Age of menarche",
      "Last menstrual period",
      "Menstruation",
      "Reason for hysterectomy",
      "Age at hysterectomy",
      "Age at menopause",
      "Gravida",
      "Para",
      "Living",
      "Abortion",
      "Age at first child",
      "1st Child",
      "2nd Child",
      "3rd Child",
      "4th Child",
      "5th Child",
      "6th Child",
      "Hypertension present",
      "K/C/O HTN",
      "Diabetes present",
      "K/C/O DM",
      "Cancer present",
      "K/C/O Cancer",
    ],
    options: {
      "ID Proof Type": ["Aadhar", "Ration Card", "Voters ID", "Not available"],
      "Number of family members": "",
      Status: ["In Person", "Absent"],
      Gender: ["Male", "Female"],
      "Marital Status": ["Single", "Married", "Widow", "Widower", "Divorced"],
      Age: numberStrings(18, 100),
      "Weight (in kgs)": numberStrings(20, 150),
      "Height (in cms)": numberStrings(100, 200),
      Religion: ["Hindu", "Muslim", "Christian", "Buddhist", "Others"],
      Education: ["No schooling", "upto 5th Standard", "upto 7th Standard", "SSLC", "PUC", "Diploma", "Graduation", "Post graduation"],
      "Occupation Group - According to NCO 2015": [
        "Legislators, Senior Officials and Managers - Group 1",
        "Professionals - Group 2",
        "Technicians and associate professionals - Group 3",
        "Clerks/Clerical support workers - Group 4",
        "Service and sales workers - Group 5",
        "Skilled agricultural, forestry and fishery workers - Group 6",
        "Craft and related trader workers - Group 7",
        "Plant and machine operators and assemblers - Group 8",
        "Elementary occupations - Group 9",
        "Workers not classified by Occupations - Group 10",
      ],
      "Estimated Annual Family Income": ["less than INR 1,25,000", "between INR 1,25,000 to INR 5,00,000", "between INR 5,00,000 to INR 30,00,000", "More than INR 30,00,000"],
      "Have you heard about cancer ?": ["Yes", "No", "Absent"],
      "Are you aware of the symptoms/warning signs of cancer?": ["Yes", "No", "Absent"],
      "Do you think tobacco causes cancer?": ["Yes", "No", "Absent"],
      "Can cancer spread from one person to another?": ["Yes", "No", "Absent"],
      "Is there treatment and cure for cancer?": ["Yes", "No", "Absent"],
      "Exposure to second hand smoke": ["At place of work", "At home", "In public", "None"],
      "Do you currently use tobacco in any form?": ["Yes", "Not Now", "Never"],
      'If answered "yes" or "not now", for how many years have you had the habit? ': ["less than 1 year", "1-5 years", "6-10 years", "11-20 years", "20-40 years", "> 40 years"],
      "If not now, how long has it been since you quit the habit? ": ["less than 1 year", "1-5 years", "6-10 years", "11-20 years", "> 20 years"],
      "Types of tobacco consumption": [
        "Smoked tobacco - beedi, cigarettes",
        "Smokeless tobacco - ghutka, hans, pan masala, snuff",
        "Betel quid with tobacco (kaddipudi, hogesoppu)",
        "Betel quid without tobacco",
        "Other",
      ],
      "Frequency of use / day [Smoked tobacco - beedi, cigarettes]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Betel quid without tobacco]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Others ]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Have you attempted to quit tobacco in the past ?": ["Yes", "No"],
      "If yes, what was the method you adopted? ": ["Substitution", "Self Control"],
      "For how many days did you quit the habit? ": ["2-3 days", "1 week", "1 month", "2-6 months"],
      "What was the reason to quit the habit?": [
        "Was not well",
        "Admitted to the hospital",
        "Family member had cancer",
        "saw some cancer patients and got scareds",
        "not good for health",
        "felt bad about my addiction",
      ],

      "Alcohol consumption status": ["Yes", "Not now", "Never"],
      "If yes, since when": ["less than 1 year", "1-5 years", "6-10 years", "11-20 years", "20-40 years", "> 40 years"],
      "If not now, how long has it been since you quit ": ["less than 1 year", "1-5 years", "6-10 years", "11-20 years", ">20 years"],
      "For how long did you consume alcohol?": ["less than 1 year", "1-5 years", "6-10 years", "11-20 years", "> 20 years"],
      "Alcohol consumption frequency": ["Daily", "Weekly", "Monthly", "Occasionally"],
      "Have you undergone any cancer screening tests before?": ["Yes", "No"],
      "If yes, when? ": ["less than a year", "1-3 years", "more than 3 years"],
      "Which cancer were you screened for?": ["Oral Cavity", "Breast", "Cervix", "Colorectal", "Prostate", "Oesophagus and stomach", "Other"],
      "What was the reason for screening?": ["Free camp", "Suspected symptoms"],
      "Was any blood related family member diagnosed with cancer?": ["Yes", "No"],
      "If yes, how many? ": ["1", "2", "3 or more"],
      "Warning signs of cancer - if any of the following complaints are present / persistent, please tick all the options that apply to you": [
        "Rapid weight loss without apparent cause",
        "Peristent cough or hoarseness of voice",
        "a scab, sore or ulcer that fails to heal in three weeks",
        "Blood in urine or stools",
        "A mole or blemish or wart that enlarges, changes in colour, bleeds or itches",
        "Any mass or growth in the body",
        "cough up bloody sputum",
        "persistent difficulty in swallowing",
        "Frequent changes in bowel and bladder habits",
        "Unusual bleeding or discharge from genital, urinary or digestive tract",
        "black sticky motion",
      ],
      "Female specific symptoms": ["A thickening or lump in breast or elsewhere", "Bleeding or dischage from the nipple", "Irregular/post menopausal bleeding", "Unusual white discharge"],
      "Menstruation stage": ["Premenopausal", "Perimenopausal", "Post menopausal", "Post hysterectomy", "Absent"],
      "Age of menarche": numberStrings(10, 20),
      "Last menstrual period": "",
      Menstruation: ["Regular", "Irregular"],
      "Reason for hysterectomy": ["prolapsed uterus", "excessive bleeding", "excessive white dischage", "post coital bleeding", "ovarian cysts", "other issues"],
      "Age at hysterectomy": numberStrings(25, 60),
      "Age at menopause": numberStrings(40, 60),
      Gravida: numberStrings(0, 20),
      Para: "",
      Living: "",
      Abortion: "",
      "Age at first child": numberStrings(15, 45),
      "1st Child": ["did not breast feed", "less than 3 months", "3-6 months", "more than 6 months"],
      "2nd Child": ["did not breast feed", "less than 3 months", "3-6 months", "more than 6 months"],
      "3rd Child": ["did not breast feed", "less than 3 months", "3-6 months", "more than 6 months"],
      "4th Child": ["did not breast feed", "less than 3 months", "3-6 months", "more than 6 months"],
      "5th Child": ["did not breast feed", "less than 3 months", "3-6 months", "more than 6 months"],
      "6th Child": ["did not breast feed", "less than 3 months", "3-6 months", "more than 6 months"],
      "Hypertension present": ["Yes", "No"],
      "K/C/O HTN": ["on treatment", "not treated", "currently not on treatment", "completed treatment"],
      "Diabetes present": ["Yes", "No"],
      "K/C/O DM": ["on treatment", "not treated", "currently not on treatment", "completed treatment"],
      "Cancer present": ["Yes", "No"],
      "K/C/O Cancer": ["on treatment", "not treated", "currently not on treatment", "completed treatment"],
    },
  },
  {
    id: 2,
    msg: "Screening",
    fields: [
      "Heart Rate",
      "SPO2",
      "BP/SBP",
      "BP/DBP",
      "GRBS",
      "Total Body Fat",
      "Subcutaneous Body Fat",
      "Visceral Body Fat",
      "Waist Circumference(in cm)",
      "Hip Circumference(in cm)",
      "Screening done for",
      "Findings",
      "Oral cavity Photos",
      "Homogenous leukoplakia",
      "Homogenous leukoplakia - Lesion dimension",
      "Non homogenous leukoplakia",
      "Non homogenous leukoplakia - Lesion dimension",
      "Erythroleukoplakia",
      "Erythroleukoplakia - Lesion dimension",
      "Erythroplakia",
      "Erythroplakia - Lesion dimension",
      "OSMF",
      "Lichen planus present",
      "Lichen planus present - Lesion location",
      "Suspicious ulcer present",
      "Suspicious ulcer present - Lesion size",
      "Suspicious growth",
      "Suspicious growth present - Lesion size",
      "Smokers Palate",
      "Oral punch biopsy indicated",
      "Laser procedure advised",
      "Breast Examination Right breast",
      "Breast Examination Left breast",
      "Abnormality location Right breast",
      "Abnormality location Left breast",
      "Breast Photos",
      "Nipple discharge",
      "Advised bilateral screening mammography",
      "Advised bilateral screening ultrasound",
      "FNAC done when indicated",
      "Nipple discharge smear taken when indicated",
      "Information",
      "Per Speculum",
      "VIA",
      "Releveant images",
      "Pap smear taken",
      "Cervical Punch biopsy indicated",
      "Recommendation",
    ],
    options: {
      "Heart Rate": numberStrings(40, 200),
      SPO2: numberStrings(40, 100),
      "BP/SBP": "",
      "BP/DBP": "",
      GRBS: "",
      "Total Body Fat": "",
      "Subcutaneous Body Fat": "",
      "Visceral Body Fat": "",
      "Waist Circumference(in cm)": "",
      "Hip Circumference(in cm)": "",
      "Screening done for": ["Oral Cancer", "Breast Cancer", "Cervical Cancer", "General check only"],
      Findings: [
        "Erythroleukoplakia",
        "Erythroplakia",
        "growth",
        "homogenous_Leukoplakia",
        "Lichen Planus",
        "NAD",
        "Neck Nodes",
        "Non homogenous leukoplakia",
        "smokers_Palate",
        "submucous_Fibrosis",
        "suspicious_ulcer",
      ],
      "Oral cavity Photos": ["With photo", "Without photo"],
      "Homogenous leukoplakia": [
        "Anterior vestibule lower",
        "Anterior vestibule upper",
        "Floor of the mouth",
        "Hard palate",
        "Lateral border of tongue left",
        "Lateral border of tongue right",
        "Left buccal mucosa",
        "Lower labial mucosa",
        "Lower left GBS",
        "Lower right GBS",
        "Retro molar trigone",
        "Right buccal mucosa",
        "Soft palate",
        "Upper labial mucosa",
        "Upper left GBS",
        "Upper right GBS",
      ],
      "Homogenous leukoplakia - Lesion dimension": ["Less than 2 cm diameter", "2-4 cm diameter", "more than 4cm diameter", "diffused"],
      "Non homogenous leukoplakia": [
        "Anterior vestibule lower",
        "Anterior vestibule upper",
        "Floor of the mouth",
        "Hard palate",
        "Lateral border of tongue left",
        "Lateral border of tongue right",
        "Left buccal mucosa",
        "Lower labial mucosa",
        "Lower left GBS",
        "Lower right GBS",
        "Retro molar trigone",
        "Right buccal mucosa",
        "Soft palate",
        "Upper labial mucosa",
        "Upper left GBS",
        "Upper right GBS",
      ],
      "Non homogenous leukoplakia - Lesion dimension": ["Less than 2 cm diameter", "2-4 cm diameter", "more than 4cm diameter", "diffused"],
      Erythroleukoplakia: [
        "Anterior vestibule lower",
        "Anterior vestibule upper",
        "Floor of the mouth",
        "Hard palate",
        "Lateral border of tongue left",
        "Lateral border of tongue right",
        "Left buccal mucosa",
        "Lower labial mucosa",
        "Lower left GBS",
        "Lower right GBS",
        "Retro molar trigone",
        "Right buccal mucosa",
        "Soft palate",
        "Upper labial mucosa",
        "Upper left GBS",
        "Upper right GBS",
      ],
      "Erythroleukoplakia - Lesion dimension": ["Less than 2 cm diameter", "2-4 cm diameter", "more than 4cm diameter", "diffused"],
      Erythroplakia: [
        "Anterior vestibule lower",
        "Anterior vestibule upper",
        "Floor of the mouth",
        "Hard palate",
        "Lateral border of tongue left",
        "Lateral border of tongue right",
        "Left buccal mucosa",
        "Lower labial mucosa",
        "Lower left GBS",
        "Lower right GBS",
        "Retro molar trigone",
        "Right buccal mucosa",
        "Soft palate",
        "Upper labial mucosa",
        "Upper left GBS",
        "Upper right GBS",
      ],
      "Erythroplakia - Lesion dimension": ["Less than 2 cm diameter", "2-4 cm diameter", "more than 4cm diameter", "diffused"],
      OSMF: ["Atrophic glossitis", "blanching", "Burning mouth", "Palpable fibrous bands", "Restricted mouth opening", "Restricted tongue movement", "Shrunken uvula"],
      "Lichen planus present": ["Atrophic LP", "Bullous LP", "Erosive LP", "Papular LP", "Plaque LP", "Reticular LP"],
      "Lichen planus present - Lesion location": ["left buccal mucosa", "right buccal mucosa"],
      "Suspicious ulcer present": [
        "Anterior vestibule lower",
        "Anterior vestibule upper",
        "Floor of the mouth",
        "Hard palate",
        "Lateral border of tongue left",
        "Lateral border of tongue right",
        "Left buccal mucosa",
        "Lower labial mucosa",
        "Lower left GBS",
        "Lower right GBS",
        "Retro molar trigone",
        "Right buccal mucosa",
        "Soft palate",
        "Upper labial mucosa",
        "Upper left GBS",
        "Upper right GBS",
      ],
      "Suspicious ulcer present - Lesion size": ["Less than 2 cm diameter", "2-4 cm diameter", "more than 4cm diameter"],
      "Suspicious growth": [
        "Anterior vestibule lower",
        "Anterior vestibule upper",
        "Floor of the mouth",
        "Hard palate",
        "Lateral border of tongue left",
        "Lateral border of tongue right",
        "Left buccal mucosa",
        "Lower labial mucosa",
        "Lower left GBS",
        "Lower right GBS",
        "Retro molar trigone",
        "Right buccal mucosa",
        "Soft palate",
        "Upper labial mucosa",
        "Upper left GBS",
        "Upper right GBS",
      ],
      "Suspicious growth present - Lesion size": ["Less than 2 cm diameter", "2-4 cm diameter", "more than 4cm diameter"],
      "Smokers Palate": ["Hard palate", "Soft palate"],
      "Oral punch biopsy indicated": ["Yes and willing", "Yes and unwilling", "No"],
      "Laser procedure advised": ["Excision", "Ablation", "NA"],
      "Breast Examination Right breast": ["Axillary Nodes palpable", "Fixed Suspicious Lump", "Freely Mobile Lump", "Nipple Discharge", "Normal", "Thickening"],
      "Breast Examination Left breast": ["Axillary Nodes palpable", "Fixed Suspicious Lump", "Freely Mobile Lump", "Nipple Discharge", "Normal", "Thickening"],
      "Abnormality location Right breast": ["Inner lower quadrant", "Inner upper quadrant", "Outer lower quadrant", "Outer upper quadrant"],
      "Abnormality location Left breast": ["Inner lower quadrant", "Inner upper quadrant", "Outer lower quadrant", "Outer upper quadrant"],
      "Breast Photos": ["With photo", "Without photo"],
      "Nipple discharge": ["Blood stained", "Grumous", "Multiple Duct", "Serous", "Single Duct"],
      "Advised bilateral screening mammography": ["Yes", "No", "Other"],
      "Advised bilateral screening ultrasound": ["Yes", "No", "Other"],
      "FNAC done when indicated": ["Yes", "No", "Other"],
      "Nipple discharge smear taken when indicated": ["Yes", "No", "Other"],
      Information: ["Irregular menstruation", "Under menstruation", "Post hysterectomy status", "Unwilling for cervical examination", "WDPV"],
      "Per Speculum": [
        "Bloody discharge present",
        "Endocervical polyp present",
        "Erosion present",
        "Growth present",
        "Lesion Present",
        "Nabothian cyst present",
        "Requires further test",
        "SCJ fully visible",
        "SCJ partially visible",
        "Strawberry cervix",
        "White discharge present",
        "VIA done last year",
        "SCJ not visible",
      ],
      VIA: ["Positive", "Negative"],
      "Releveant images": ["With photo", "Without photo"],
      "Pap smear taken": ["Yes", "Unwilling"],
      "Cervical Punch biopsy indicated": ["Yes and willing", "Yes and unwilling", "No"],
      Recommendation: [
        "No intervention",
        "Recommendation to hospital",
        "Local Procedure-Laser",
        "Local Procedure-Ultrasound",
        "Local Procedure-Mammography",
        "Local Procedure-Colposcopy",
        "Next screening date",
      ],
    },
  },
  {
    id: 3,
    msg: "TCC",
    fields: [
      "Amount spent on tobacco per day",
      "Types of tobacco consumption",
      "Frequency of use / day [Smoked tobacco - beedi, cigarettes]",
      "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]",
      "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]",
      "Frequency of use / day [Betel quid without tobacco]",
      "Frequency of use / day [Others ]",
      "For how many years have you had the habit?",
      "Family history of Tobacco use",
      "Family history of Substance use",
      "Family history of Mental disorder use",
      "Age of uptake",
      "Reason for uptake / Starting the habit",
      "I smoke to keep myself alert",
      "Smoking is pleasant and relaxing",
      "I smoke when I am upset about something",
      "I smoke out of boredom",
      "If I run out of cigarette/beedi, I find it unbearable.",
      "I smoke automatically without being aware of it.",
      "I smoke to perk myself up.",
      "I find it difficult to go about my job without smoking",
      "I need to smoke in order to pass motion.",
      "I get real cravings for cigarette/beedi when I haven't used in a while",
      "I use it to keep from slowing down",
      "I like the texture and taste of it in my mouth.",
      "I find it pleasant and relaxing",
      "I use it when I am upset about something",
      "I chew it out of boredom.",
      "If I run out of it, I find it unbearable.",
      "I believe that it provides calcium.",
      "I use it to perk myself up.",
      "It relieves pain in my jaw/teeth.",
      "I find it difficult to go about with my job without it.",
      "Fagerstorm Test for Nicotine Dependence - How soon after you wake up do you smoke your first cigarette?",
      "Fagerstorm Test for Nicotine Dependence - Do you find it difficult to refrain from smoking in places where it is forbidden, e.g., temples, during an outing with family, during village festivities?",
      "Fagerstorm Test for Nicotine Dependence - Which cigarette would you hate most to give up?",
      "Fagerstorm Test for Nicotine Dependence - How many cigarettes per day do you smoke?",
      "Fagerstorm Test for Nicotine Dependence - Do you smoke more frequently during the first hours of waking than during the rest of the day?",
      "Fagerstorm Test for Nicotine Dependence - Do you smoke even if you are sick in bed?",
      "Modified Fagerstorm Test - How soon after you wake up do you place your first dip?",
      "Modified Fagerstorm Test - How often do you intentionally swallow its juice?",
      "Modified Fagerstorm Test - Which chew would you hate most to give up?",
      "Modified Fagerstorm Test - How many cans/pouches per week do you use?",
      "Modified Fagerstorm Test - Do you chew more frequently during the first hours after waking than during the rest of the day?",
      "Modified Fagerstorm Test - Do you chew even if you are sick in the bed?",
      "Do you intend to quit the habit",
      "Have you previously attempted to quit the habit?",
      "what among the following were the barriers to quit?",
      "Do you often forget the intention behind quitting?",
      "Did you have the right social support?",
      "Are you fearful of what might happen if you quit?",
      "Are you anticipating sadness when you quit?",
      "Do you find yourself thinking about death?",
      "Do you wish to live a healthy life?",
      "Do you believe that using tobacco is healthy?",
      "Does anyone in the family believe your habits are unhealthy?",
      "Would you agree if someone told you that use of tobacco in any form is not healthy?",
      "Are you thinking of quitting the habit now?",
      "Do you think that quitting takes a lot of effort?",
      "Do your family support you in quitting the habit?",
      "Do your friends support you in quitting the habit?",
      "Would you be willing to quit if someone from the family puts in the same effort to help?",
      "Would it be helpful if the counsellor gave you a nudge every now and then?",
      "Would you need some time to think whether you want to quit or not?",
      "Do you believe you are capable of quitting?",
      "Do you believe you can quit on your own?",
      "If there were professionals to help you out would you make an effort to quit?",
      "Which form of professional intervention would you prefer ?",
      "Which mode of therapy would you prefer?",
      "Dependency score for smoke tobacco",
      "Dependency level for smoke tobacco",
      "Dependency score for chewing habits",
      "Dependency level for smokeless tobacco",
      "Motivation stage assessed",
      "Counselling Techniques",
    ],
    options: {
      "Amount spent on tobacco per day": "",
      "Types of tobacco consumption": [
        "Smoked tobacco - beedi, cigarettes",
        "Smokeless tobacco - ghutka, hans, pan masala, snuff",
        "Betel quid with tobacco (kaddipudi, hogesoppu)",
        "Betel quid without tobacco",
        "Other",
      ],
      "Frequency of use / day [Smoked tobacco - beedi, cigarettes]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Betel quid without tobacco]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "Frequency of use / day [Others ]": ["less then 5", "five to ten", "eleven to twenty", "greater then twenty"],
      "For how many years have you had the habit?": ["less than 1 year", "1-5 years", "6-10 years", "11-20 years", "20-40 years", "> 40 years"],
      "Family history of Tobacco use": ["Yes", "No", "Not Known"],
      "Family history of Substance use": ["Yes", "No", "Not Known"],
      "Family history of Mental disorder use": ["Yes", "No", "Not Known"],
      "Age of uptake": ["5 - 15", "16 - 25", "26 - 35", "36 - 55", "> 55"],
      "Reason for uptake / Starting the habit": [
        "Since childhood",
        "Dental issues",
        "Learnt from elders of the family",
        "Peer influence",
        "Due to work stress",
        "Family problems",
        "Sleep issues",
        "Boredom",
        "During or after pregnancy",
        "Not known",
        "Others",
      ],
      "I smoke to keep myself alert": ["Always", "Often", "Occasionally"],
      "Smoking is pleasant and relaxing": ["Always", "Often", "Occasionally"],
      "I smoke when I am upset about something": ["Always", "Often", "Occasionally"],
      "I smoke out of boredom": ["Always", "Often", "Occasionally"],
      "If I run out of cigarette/beedi, I find it unbearable.": ["Always", "Often", "Occasionally"],
      "I smoke automatically without being aware of it.": ["Always", "Often", "Occasionally"],
      "I smoke to perk myself up.": ["Always", "Often", "Occasionally"],
      "I find it difficult to go about my job without smoking": ["Always", "Often", "Occasionally"],
      "I need to smoke in order to pass motion.": ["Always", "Often", "Occasionally"],
      "I get real cravings for cigarette/beedi when I haven't used in a while": ["Always", "Often", "Occasionally"],

      "I use it to keep from slowing down": ["Always", "Often", "Occasionally"],
      "I like the texture and taste of it in my mouth.": ["Always", "Often", "Occasionally"],
      "I find it pleasant and relaxing": ["Always", "Often", "Occasionally"],

      "I use it when I am upset about something": ["Always", "Often", "Occasionally"],
      "I chew it out of boredom.": ["Always", "Often", "Occasionally"],
      "If I run out of it, I find it unbearable.": ["Always", "Often", "Occasionally"],
      "I believe that it provides calcium.": ["Always", "Often", "Occasionally"],
      "I use it to perk myself up.": ["Always", "Often", "Occasionally"],
      "It relieves pain in my jaw/teeth.": ["Always", "Often", "Occasionally"],
      "I find it difficult to go about with my job without it.": ["Always", "Often", "Occasionally"],
      "Fagerstorm Test for Nicotine Dependence - How soon after you wake up do you smoke your first cigarette?": ["Within 5 minutes", "6-30 minutes", "31-60 minutes", "After 60 minutes"],
      "Fagerstorm Test for Nicotine Dependence - Do you find it difficult to refrain from smoking in places where it is forbidden, e.g., temples, during an outing with family, during village festivities?":
        ["Yes", "No"],
      "Fagerstorm Test for Nicotine Dependence - Which cigarette would you hate most to give up?": ["The first one in the morning", "Any other"],
      "Fagerstorm Test for Nicotine Dependence - How many cigarettes per day do you smoke?": ["Thirty one or more", "Twenty one-Thirty", "Eleven-Twenty", "Ten or less"],
      "Fagerstorm Test for Nicotine Dependence - Do you smoke more frequently during the first hours of waking than during the rest of the day?": ["Yes", "No"],
      "Fagerstorm Test for Nicotine Dependence - Do you smoke even if you are sick in bed?": ["Yes", "No"],
      "Modified Fagerstorm Test - How soon after you wake up do you place your first dip?": ["Within 5 minutes", "6-30 minutes", "31-60 minutes", "After 60 minutes"],
      "Modified Fagerstorm Test - How often do you intentionally swallow its juice?": ["Always", "Sometimes", "Never"],
      "Modified Fagerstorm Test - Which chew would you hate most to give up?": ["The first one in the morning", "Any other"],
      "Modified Fagerstorm Test - How many cans/pouches per week do you use?": ["More than Three", "Two-Three", "One"],
      "Modified Fagerstorm Test - Do you chew more frequently during the first hours after waking than during the rest of the day?": ["Yes", "No"],
      "Modified Fagerstorm Test - Do you chew even if you are sick in the bed?": ["Yes", "No"],
      "Do you intend to quit the habit": ["Yes", "No"],
      "Have you previously attempted to quit the habit?": ["Yes", "No"],
      "what among the following were the barriers to quit?": [
        "Stress",
        "Craving",
        "Sleeplessness",
        "Disinterest in work",
        "Irritability",
        "Anxiety",
        "Unable to pass bowel movements",
        "Boredom",
        "Peer pressure",
        "Headache",
        "Others",
      ],
      "Do you often forget the intention behind quitting?": ["Yes", "No"],
      "Did you have the right social support?": ["Yes", "No"],
      "Are you fearful of what might happen if you quit?": ["Yes", "No"],
      "Are you anticipating sadness when you quit?": ["Yes", "No"],
      "Do you find yourself thinking about death?": ["Yes", "No"],
      "Do you wish to live a healthy life?": ["Yes", "No"],
      "Do you believe that using tobacco is healthy?": ["Yes", "No"],
      "Does anyone in the family believe your habits are unhealthy?": ["Yes", "No"],
      "Would you agree if someone told you that use of tobacco in any form is not healthy?": ["Yes", "No"],
      "Are you thinking of quitting the habit now?": ["Yes", "No"],
      "Do you think that quitting takes a lot of effort?": ["Yes", "No"],
      "Do your family support you in quitting the habit?": ["Yes", "No"],
      "Do your friends support you in quitting the habit?": ["Yes", "No"],
      "Would you be willing to quit if someone from the family puts in the same effort to help?": ["Yes", "No"],
      "Would it be helpful if the counsellor gave you a nudge every now and then?": ["Yes", "No"],
      "Would you need some time to think whether you want to quit or not?": ["Yes", "No"],
      "Do you believe you are capable of quitting?": ["Yes", "No"],
      "Do you believe you can quit on your own?": ["Yes", "No"],
      "If there were professionals to help you out would you make an effort to quit?": ["Yes", "No"],
      "Which form of professional intervention would you prefer ?": ["Individualized", "Peer Group"],
      "Which mode of therapy would you prefer?": ["Inperson", "Telephonic"],
      "Dependency score for smoke tobacco": "",
      "Dependency level for smoke tobacco": ["Low dependence", "Low to moderate dependence", "Moderate dependence", "High dependence"],
      "Dependency score for chewing habits": "",
      "Dependency level for smokeless tobacco": ["Low dependence", "Low to moderate dependence", "Moderate dependence", "High dependence"],
      "Motivation stage assessed": ["Pre-Contemplation", "Contemplation", "Action", "Maintenance", "Preparation", "Relapse"],
      "Counselling Techniques": ["Solution Focused Brief Therapy Techniques", "Motivational Enhancement techniques", "Brief advice"],
    },
  },
  {
    id: 4,
    msg: "General",
    fields: ["Village", "Panchayath", "Date"],
    options: {
      Panchayath: [
        { name: "Anoor", id: "01" },
        { name: "Batlahalli", id: "02" },
        { name: "Bhoomishettyhalli", id: "03" },
        { name: "Burudugunte", id: "04" },
        { name: "Chilakalanerupu", id: "05" },
        { name: "Chinnasandra", id: "06" },
        { name: "Chintamani", id: "07" },
        { name: "Doddaganjuru ", id: "08" },
        { name: "Herekatigenahalli", id: "09" },
        { name: "Iragampalli", id: "10" },
        { name: "Kadadanamari ", id: "11" },
        { name: "Kagathi", id: "12" },
        { name: "Kaiwara", id: "13" },
        { name: "Kathriguppe", id: "14" },
        { name: "Kencharlahalli", id: "15" },
        { name: "Konapalli", id: "16" },
        { name: "Korlaparthy", id: "17" },
        { name: "Kotagal", id: "18" },
        { name: "Kuruburu", id: "19" },
        { name: "M Gollahalli", id: "20" },
        { name: "Masthenahalli", id: "21" },
        { name: "Mindigal", id: "22" },
        { name: "Mitthalli", id: "23" },
        { name: "Munaganahalli", id: "24" },
        { name: "Murugamalla", id: "25" },
        { name: "Nandiganahalli", id: "26" },
        { name: "Pedduru ", id: "27" },
        { name: "Peramachanahalli", id: "28" },
        { name: "S Raguttahalli ", id: "29" },
        { name: "Santhekallahalli", id: "30" },
        { name: "Shettihalli", id: "31" },
        { name: "Talagavara", id: "32" },
        { name: "Upparapete", id: "33" },
        { name: "Yagavakote", id: "34" },
        { name: "Yenigdale", id: "35" },
        { name: "Oolavadi ", id: "36" },
      ],
      Village: [
        { name: "Anoor", id: "01001" },
        { name: "Moodalachinthanahalli", id: "01002" },
        { name: "Doddabommanahalli", id: "01003" },
        { name: "Panasachowdanahalli", id: "01004" },
        { name: "Chikkapura", id: "01005" },
        { name: "Doddapura", id: "01006" },
        { name: "G.Kodihalli ", id: "01007" },
        { name: "K.Hosur", id: "01008" },
        { name: "Krishnamanahosahalli", id: "01009" },
        { name: "Vishwanathapura", id: "01010" },
        { name: "Chikkabommanahalli", id: "01011" },
        { name: "Kambalahalli", id: "02013" },
        { name: "Musturapattana", id: "02014" },
        { name: "Konapura", id: "02015" },
        { name: "Ragimakalahalli", id: "02016" },
        { name: "Batlahalli(Batlahalli)", id: "02017" },
        { name: "Yanamalapadi ", id: "02018" },
        { name: "Channarayanhalli", id: "02019" },
        { name: "Somakallahalli", id: "02020" },
        { name: "Bodampalli", id: "02021" },
        { name: "Kapalli(Bhoomishettyhalli)", id: "03022" },
        { name: "Bhoomishettyhalli", id: "03023" },
        { name: "Moogalamari", id: "03024" },
        { name: "Siddepalli", id: "03025" },
        { name: "Domalahalli", id: "03026" },
        { name: "Gudamarlahalli", id: "03027" },
        { name: "Kanishettyhalli", id: "03028" },
        { name: "Somayajalahalli", id: "03029" },
        { name: "Chowdareddy Palya(Bhoomishettyhalli)", id: "03030" },
        { name: "Agrahara(Bhoomishettyhalli)", id: "03031" },
        { name: "Alapalli", id: "03032" },
        { name: "Bairasandra", id: "03033" },
        { name: "Gondiwarlahalli", id: "03034" },
        { name: "Upparlahalli", id: "03035" },
        { name: "Basavapura", id: "04036" },
        { name: "Konepalli", id: "04037" },
        { name: "Burudugunte", id: "04038" },
        { name: "Krishnapura(Burudugunte)", id: "04039" },
        { name: "Deshamwarahalli", id: "04040" },
        { name: "Gadigavarahalli", id: "04042" },
        { name: "Salamakalahalli", id: "04043" },
        { name: "Mahadevapura", id: "04044" },
        { name: "Maravapalli", id: "04045" },
        { name: "Battallapura", id: "04046" },
        { name: "Chikkakuruburahalli", id: "04047" },
        { name: "Anupalli(Burudugunte)", id: "04434" },
        { name: "Chilakalanerupu", id: "05048" },
        { name: "Hosahudya", id: "05049" },
        { name: "Bedhalahalli", id: "05050" },
        { name: "T. Gollahalli", id: "05051" },
        { name: "Dvarapalli(Chilakalanerpu)", id: "05052" },
        { name: "Devapalli", id: "05053" },
        { name: "Dharmavarahalli ", id: "05054" },
        { name: "Minchilahalli", id: "05055" },
        { name: "Tuluvanuru", id: "05056" },
        { name: "Chinnasandra", id: "06057" },
        { name: "Doddahalli", id: "06059" },
        { name: "Nallaguttahalli(Chinnasandra)", id: "06060" },
        { name: "Narayanahalli", id: "06061" },
        { name: "Suladenahalli", id: "06058" },
        { name: "Agrahara(Chintamani)", id: "07078" },
        { name: "Anjani", id: "07070" },
        { name: "Ashwini Layout", id: "07086" },
        { name: "Chintamani ", id: "07066" },
        { name: "Chintamani Town", id: "07064" },
        { name: "Chinthamani ", id: "07085" },
        { name: "Gandhinagar", id: "07075" },
        { name: "Idily Palya ", id: "07074" },
        { name: "J J Colony", id: "07077" },
        { name: "Kanampalli", id: "07069" },
        { name: "Maalapalli", id: "07068" },
        { name: "N N T Road", id: "07084" },
        { name: "New Venkateshwara ", id: "07076" },
        { name: "New Venkateshwara Ward", id: "07067" },
        { name: "Prabhakar Layout", id: "07087" },
        { name: "Shanthinagar", id: "07079" },
        { name: "Sonnashettyhalli ", id: "07071" },
        { name: "Sriramnagar", id: "07083" },
        { name: "Tank Bunk Road", id: "07082" },
        { name: "Thappeshwara Colony", id: "07072" },
        { name: "Thimmasandra", id: "07081" },
        { name: "Vayuputhra Nagara", id: "07088" },
        { name: "Venkatagirikote", id: "07080" },
        { name: "Vinayaka Nagara ", id: "07073" },
        { name: "Doddaganjuru ", id: "08089" },
        { name: "Gollahalli(Doddaganjuru)", id: "08090" },
        { name: "Haadigere", id: "08091" },
        { name: "Kadadhavadi", id: "08092" },
        { name: "Shinganahalli", id: "08093" },
        { name: "Siddhimatta", id: "08094" },
        { name: "Doddanatta", id: "08095" },
        { name: "Cheemanahalli", id: "08096" },
        { name: "Chinnakeshavapura", id: "09097" },
        { name: "Herekattigenahalli", id: "09098" },
        { name: "Chikkakatiganhalli\n", id: "09099" },
        { name: "Nidagagurki", id: "09100" },
        { name: "Rachapura", id: "09101" },
        { name: "Bylahalli", id: "09102" },
        { name: "Maadarakallu", id: "09103" },
        { name: "Jeeradahalli", id: "09104" },
        { name: "Karadigutta", id: "09105" },
        { name: "Jangamapura", id: "09106" },
        { name: "Nernakallu", id: "09107" },
        { name: "Iragampalli", id: "10108" },
        { name: "Guntipalli", id: "10109" },
        { name: "Gundikere", id: "10110" },
        { name: "Seetharampura", id: "10111" },
        { name: "Mykapothahalli", id: "10112" },
        { name: "I Kurupalli", id: "10113" },
        { name: "Junjunahalli", id: "10115" },
        { name: "Bodanamari ", id: "10116" },
        { name: "Guddamapalli", id: "10424" },
        { name: "Yanamalavadlahalli", id: "10425" },
        { name: "Kodigal ", id: "11117" },
        { name: "Cheemalagatta", id: "11118" },
        { name: "Ankalamadagu ", id: "11119" },
        { name: "Bilandlahalli ", id: "11120" },
        { name: "Pongupalli", id: "11121" },
        { name: "Kadadanamari", id: "11122" },
        { name: "Sunnappagutta", id: "11123" },
        { name: "Obballapura ", id: "11124" },
        { name: "Hanumayyagarahalli", id: "11125" },
        { name: "Bhodagundalahalli", id: "11126" },
        { name: "Krishnapura(Kadadanamari)", id: "11127" },
        { name: "Dinnemindahalli/Hanumantharayanahalli", id: "11128" },
        { name: "Puttagundlahalli", id: "11129" },
        { name: "Kagathi", id: "12130" },
        { name: "Diguru", id: "12131" },
        { name: "Chokkareddyhalli", id: "12132" },
        { name: "Badagavarahalli", id: "12133" },
        { name: "Krishnarajapura", id: "12134" },
        { name: "Kariyapalli(Kagathi)", id: "12135" },
        { name: "Hiranyapalli ", id: "12136" },
        { name: "Bacchavarahalli ", id: "12137" },
        { name: "Munthakadirenahalli", id: "12138" },
        { name: "Bukkanahalli", id: "12139" },
        { name: "Singasandra", id: "12140" },
        { name: "Kaiwara", id: "13141" },
        { name: "Bannahalli", id: "13144" },
        { name: "Gudisallu", id: "13143" },
        { name: "Shyamarao Hossapette", id: "13142" },
        { name: "Ullappanahalli", id: "14145" },
        { name: "Husseinpura", id: "14146" },
        { name: "Bhaktaralli", id: "14147" },
        { name: "Kathriguppe", id: "14148" },
        { name: "Lakshmidevanakote", id: "14149" },
        { name: "Korlahalli", id: "14150" },
        { name: "Srinivas Pura", id: "14151" },
        { name: "Nalamachanahalli", id: "14152" },
        { name: "Husmanpura", id: "14153" },
        { name: "Kodigenahalli", id: "14154" },
        { name: "Kaddishanahalli", id: "14155" },
        { name: "Yarshigenahalli", id: "14156" },
        { name: "Mallikarjunapura", id: "14432" },
        { name: "Kanganahalli", id: "14433" },
        { name: "Shettynayakanahalli", id: "15158" },
        { name: "Nadampalli ", id: "15159" },
        { name: "Marabalahalli ", id: "15160" },
        { name: "Gowdanahalli ", id: "15161" },
        { name: "Kodegundlu ", id: "15162" },
        { name: "Tuvakalahalli", id: "15163" },
        { name: "Kencharlahalli ", id: "15164" },
        { name: "Chokkanahalli(Konapalli)", id: "16430" },
        { name: "Dhanamittenahalli", id: "16171" },
        { name: "Gounigadde", id: "16173" },
        { name: "Kavalagaanahalli", id: "16172" },
        { name: "Konapalli(Konapalli)", id: "16170" },
        { name: "Mohammedpura", id: "16166" },
        { name: "Nagasandragadde", id: "16431" },
        { name: "Nayanahalli", id: "16167" },
        { name: "Subbarayanapete(Konapalli)", id: "16169" },
        { name: "Swarapalli ", id: "16168" },
        { name: "  K Gollahalli", id: "17179" },
        { name: "Bacchaganahalli", id: "17439" },
        { name: "Bandenahalli", id: "17178" },
        { name: "Changavarahalli", id: "17176" },
        { name: "Gajavaarahalli", id: "17182" },
        { name: "Jangalahalli", id: "17187" },
        { name: "K. Devaganahalli", id: "17183" },
        { name: "Kadiraenahalli", id: "17180" },
        { name: "Kalakasandra", id: "17190" },
        { name: "Korlaparthy", id: "17181" },
        { name: "Kothappanahalli", id: "17177" },
        { name: "Maniyaramuddalahalli", id: "17184" },
        { name: "Masanahalli", id: "17188" },
        { name: "Neradaguttahalli", id: "17185" },
        { name: "Paapathimmenahalli", id: "17175" },
        { name: "Polanayakanahalli", id: "17192" },
        { name: "Rampamtatti", id: "17189" },
        { name: "Seegalaguttahalli", id: "17186" },
        { name: "Yarammareddyhalli", id: "17174" },
        { name: "Addepalli ", id: "18206" },
        { name: "Dhoddahalli ", id: "18194" },
        { name: "Gopalapura", id: "18205" },
        { name: "Jagatanahalli ", id: "18200" },
        { name: "K. Raguttahalli ", id: "18198" },
        { name: "K.Golahalli", id: "18204" },
        { name: "Kotagal", id: "18193" },
        { name: "Kothuru Matta", id: "18203" },
        { name: "Kumarlahalli ", id: "18195" },
        { name: "Narasapura ", id: "18197" },
        { name: "Sujjanahalli", id: "18196" },
        { name: "Thippanahalli", id: "18201" },
        { name: "Vanasanthahalli", id: "18199" },
        { name: "Veerapalli", id: "18202" },
        { name: "Kootharajanahalli", id: "19207" },
        { name: "Gadadasanahalli", id: "19208" },
        { name: "Yadahalli", id: "19209" },
        { name: "Seekal", id: "19210" },
        { name: "Kuruburu", id: "19211" },
        { name: "Gajallahalli", id: "19212" },
        { name: "Bandharlahalli", id: "19213" },
        { name: "Ramenhalli", id: "19214" },
        { name: "Mylandlahalli", id: "19215" },
        { name: "Munganahalli(M Gollahalli)", id: "20216" },
        { name: "Venkatarayanakote", id: "20217" },
        { name: "Kondliganahalli ", id: "20218" },
        { name: "Chinthapalli", id: "20219" },
        { name: "Seethampalli ", id: "20220" },
        { name: "M Gollahalli ", id: "20221" },
        { name: "YagavDhevapalli ", id: "20223" },
        { name: "Yarraiahgarahalli", id: "20224" },
        { name: "Lakkepalli", id: "20225" },
        { name: "Kapalli(M Gollahalli)", id: "20226" },
        { name: "Guttapalya", id: "20227" },
        { name: "Palligadda", id: "20228" },
        { name: "Digavdhevapalli", id: "20229" },
        { name: "Timbandhe", id: "20230" },
        { name: "Channarayanagadde", id: "20231" },
        { name: "Dhevapalli ", id: "20426" },
        { name: "Chowdareddypalya(M Gollahalli)", id: "20435" },
        { name: "Masthenahalli", id: "21232" },
        { name: "Bodgooru", id: "21238" },
        { name: "Guttahalli", id: "21234" },
        { name: "Hullugummanahalli", id: "21237" },
        { name: "Jangamaseegenahalli", id: "21236" },
        { name: "Marappahalli", id: "21235" },
        { name: "T. Hossuru", id: "21233" },
        { name: "Bandakote", id: "22239" },
        { name: "Nernihalli", id: "22240" },
        { name: "Subbrayyanapalya", id: "22241" },
        { name: "Nallarallahalli", id: "22242" },
        { name: "Battalahalli(Mindigal)", id: "22243" },
        { name: "Gutturu", id: "22244" },
        { name: "Mindigal", id: "22442" },
        { name: "Yendahalli", id: "22245" },
        { name: "Boodanamari", id: "22246" },
        { name: "Gudasalahalli", id: "22247" },
        { name: "Vegalahalli ", id: "22249" },
        { name: "Boomalatapura", id: "22250" },
        { name: "Gollahalli(Mindigal)", id: "22251" },
        { name: "Digav mindigal", id: "22252" },
        { name: "Yegav mindigal", id: "22253" },
        { name: "Anupalli(Mitthalli)", id: "23254" },
        { name: "Raspalli", id: "23255" },
        { name: "Gonenahalli", id: "23256" },
        { name: "Amitthalli", id: "23257" },
        { name: "Kommepalli", id: "23258" },
        { name: "Kattigenahalli", id: "23259" },
        { name: "Mitthalli", id: "23260" },
        { name: "Nandanavana", id: "23261" },
        { name: "Nandanahosalli", id: "23263" },
        { name: "Rangenahalli", id: "23264" },
        { name: "Doddaguttahalli", id: "23265" },
        { name: "Gurrampalli", id: "23266" },
        { name: "Agraharahalli", id: "23267" },
        { name: "Appasanahalli", id: "23268" },
        { name: "Venkatareddypalya", id: "23436" },
        { name: "Munaganahalli(Munaganahalli)", id: "24269" },
        { name: "Alamgiri", id: "24275" },
        { name: "Bidaganahalli", id: "24277" },
        { name: "Brahmanadinne", id: "24278" },
        { name: "Hosahalli", id: "24276" },
        { name: "Kachahalli", id: "24274" },
        { name: "Kachihalli", id: "24427" },
        { name: "Kallahalli", id: "24271" },
        { name: "Katamachanahalli", id: "24272" },
        { name: "Kuratihalli", id: "24273" },
        { name: "Ramapura", id: "24437" },
        { name: "Chetlapalligadda", id: "24270" },
        { name: "Murugamalla ", id: "25279" },
        { name: "Doddakarakamakanahalli", id: "25280" },
        { name: "Gudarlahalli", id: "25281" },
        { name: "Yerakote", id: "25282" },
        { name: "Gollahalli(Murugamalla)", id: "25283" },
        { name: "Gundlahalli(Murugamalla)", id: "25284" },
        { name: "Bathlahallo(Murugamalla)", id: "25285" },
        { name: "Bynahalli", id: "25286" },
        { name: "Shettihalli(Murugamalla)", id: "25287" },
        { name: "Duganarepalli", id: "25288" },
        { name: "Chalamakote", id: "25289" },
        { name: "Yarramantapalli", id: "25290" },
        { name: "Barlahalli", id: "26301" },
        { name: "Chikkakarakamakanahalli", id: "26294" },
        { name: "Dandupalya", id: "26293" },
        { name: "Gandraganahalli", id: "26297" },
        { name: "Gopalli", id: "26292" },
        { name: "Hannenahalli", id: "26291" },
        { name: "Jogganahalli", id: "26298" },
        { name: "Marinayakanahalli ", id: "26299" },
        { name: "Muddalahalli", id: "26296" },
        { name: "Nandiganahalli", id: "26295" },
        { name: "Nimmakayalahalli ", id: "26300" },
        { name: "Oolavadi", id: "36414" },
        { name: "Bathalahalli(Oolavadi)", id: "36416" },
        { name: "Bhoramakalahalli", id: "36417" },
        { name: "Gopasandra", id: "36418" },
        { name: "Handijogigadde", id: "36422" },
        { name: "Hebbari", id: "36419" },
        { name: "Imareddyhalli", id: "36420" },
        { name: "Kurrapalli", id: "36421" },
        { name: "Madikeri", id: "36415" },
        { name: " Mini kambalahalli", id: "36423" },
        { name: "Gaunicheruvupalli", id: "27302" },
        { name: "Korukonahalli", id: "27303" },
        { name: "Bodugundlahalli", id: "27304" },
        { name: "Pedduru", id: "27305" },
        { name: "Maniganahalli", id: "27306" },
        { name: "Thummallahalli ", id: "27307" },
        { name: "Neelapalli", id: "27308" },
        { name: "Kottapalli", id: "27309" },
        { name: "Nagarajapalli ", id: "27310" },
        { name: "Digvakote", id: "27311" },
        { name: "Patakote", id: "27312" },
        { name: "Vemapalli", id: "27313" },
        { name: "Kadirappanayakanakote", id: "27314" },
        { name: "Diguapalli ", id: "27315" },
        { name: "Chapura", id: "28318" },
        { name: "Gunnahalli", id: "28322" },
        { name: "Kendanahalli", id: "28428" },
        { name: "Konganahalli", id: "28321" },
        { name: "Madabahalli", id: "28324" },
        { name: "Mylapura", id: "28323" },
        { name: "Nagadenahalli ", id: "28326" },
        { name: "Nayindra Colony", id: "28325" },
        { name: "Nayindrahalli", id: "28319" },
        { name: "Peramachanahalli", id: "28317" },
        { name: "Venkatapura(Peramachanahalli)", id: "28320" },
        { name: "S Raguttahalli ", id: "29327" },
        { name: "Kariyapalli(S Raguttahalli)", id: "29328" },
        { name: "Mavvukere", id: "29329" },
        { name: "Yasagalahali", id: "29330" },
        { name: "Y Gollahalli", id: "29331" },
        { name: "Nallaguttahalli(S Raguttahalli)", id: "29332" },
        { name: "Kanchinayakanahalli ", id: "29333" },
        { name: "Guddivabanahalli", id: "29334" },
        { name: "Madhamangala", id: "29335" },
        { name: "Bhujangarayanakote ", id: "29336" },
        { name: " Eetamakalahalli       ", id: "29337" },
        { name: "Konapalli(S Raguttahalli)", id: "29338" },
        { name: "Brahamanahalli", id: "29339" },
        { name: "Nagarajahosahalli", id: "29340" },
        { name: "Bommalatapura", id: "29429" },
        { name: "Akkimangala", id: "30341" },
        { name: "Hirepalya", id: "30342" },
        { name: "Bacchapanahalli", id: "30343" },
        { name: "Beejeranahalli", id: "30344" },
        { name: "Virupakshapura", id: "30345" },
        { name: "Kadirapura", id: "30346" },
        { name: "Vychakuru", id: "30347" },
        { name: "Santhekallahalli", id: "30348" },
        { name: "Surappanahalli", id: "30349" },
        { name: "Chikkamunimangala(Santhekallahalli)", id: "30440" },
        { name: "Chikkamunimangala(Shettihalli)", id: "31350" },
        { name: "Dwarapalli(Shettihalli)", id: "31351" },
        { name: "Venkatapura(Shettihalli)", id: "31352" },
        { name: "Shettihalli(Shettihalli)", id: "31353" },
        { name: "Jaladenahalli", id: "31354" },
        { name: "Kethanayakanahalli", id: "31355" },
        { name: "Paalenahalli", id: "31356" },
        { name: "Thammenahalli", id: "31357" },
        { name: "Masilahalli", id: "31358" },
        { name: "Anakallu", id: "31359" },
        { name: "Bandamidahalli ", id: "31360" },
        { name: "Chowdadenahalli", id: "31361" },
        { name: "Gounahalli", id: "31362" },
        { name: "Nallamachanahalli", id: "31363" },
        { name: "Karakamalahalli", id: "31364" },
        { name: "Yashwanthpura", id: "31365" },
        { name: "Doddamunimangala", id: "31438" },
        { name: "Talagavara", id: "32366" },
        { name: "Attooru", id: "32372" },
        { name: "Jodi Hosahalli", id: "32368" },
        { name: "Mallikapura", id: "32370" },
        { name: "Muthakadhahalli", id: "32371" },
        { name: "Subbarayanapete(Talagavara)", id: "32369" },
        { name: "Vadahalli(Talagavara)", id: "32367" },
        { name: "Thinakallu", id: "33373" },
        { name: "Amitganahalli", id: "33374" },
        { name: "A Guttahalli", id: "33375" },
        { name: "Chandrahalli ", id: "33376" },
        { name: "Rayapalli", id: "33377" },
        { name: "Binganahalli", id: "33378" },
        { name: "Kempadhenahalli", id: "33379" },
        { name: "Vaddahalli(Upparapete)", id: "33380" },
        { name: "Chikkakondrahalli", id: "33381" },
        { name: "Dodda Kondahalli", id: "33382" },
        { name: "Bhuragamakalahalli", id: "33383" },
        { name: "Upparapete", id: "33384" },
        { name: "Sorrapalli", id: "33385" },
        { name: "Goobalahalli", id: "33386" },
        { name: "Bommekallu", id: "33387" },
        { name: "Kottahudya", id: "34388" },
        { name: "Kanagamakalahalli", id: "34389" },
        { name: "Y. Kurapalli", id: "34390" },
        { name: "Dinnamindahalli", id: "34391" },
        { name: "Naramakahalli", id: "34392" },
        { name: "Pullagundalahalli", id: "34393" },
        { name: "Yagavakote ", id: "34394" },
        { name: "Gunthurugadde", id: "34395" },
        { name: "Paslanayakanahalli", id: "34396" },
        { name: "Kondavenakapalli", id: "34397" },
        { name: "Yenigdale", id: "35398" },
        { name: "Ulibele", id: "35399" },
        { name: "Gundlahalli(Yenigdale)", id: "35400" },
        { name: "Chinnapalli", id: "35401" },
        { name: "Motamakalahalli", id: "35402" },
        { name: "Chintamakalahalli ", id: "35403" },
        { name: "Kanchepalli", id: "35404" },
        { name: "Balareddyhalli", id: "35405" },
        { name: "Chokkanahalli(Yenigdale)", id: "35406" },
        { name: "Nakkalokihalli ", id: "35407" },
        { name: "Bommepalli", id: "35408" },
        { name: "Gengiredipalya", id: "35409" },
        { name: "Vangimallu", id: "35410" },
        { name: "Kacchanahalli", id: "35411" },
        { name: "Gorludoddihalli", id: "35412" },
        { name: "Varadenahalli", id: "35413" },
      ],
      Date: [{ SDate: "", LDate: "" }],
    },
  },
];

export default data;
