export const patientNode = [
  "Individual Unique ID",
  "Name",
  "ID Proof Type",
  "ID Proof Number",
  "Number of family members",
  "Status",
  "Gender",
  "Contact number",
  "Marital Status",
  "Father's Name",
  "Mother's Name",
  "Age",
  "Weight (in kgs)",
  "Height (in cms)",
  "Religion",
  "Education",
  "Occupation Group - According to NCO 2015",
  "Estimated Annual Family Income",
];
export const form_1Node = [
  "Have you heard about cancer ?",
  "Are you aware of the symptoms/warning signs of cancer?",
  "Do you think tobacco causes cancer?",
  "Can cancer spread from one person to another?",
  "Is there treatment and cure for cancer?",
  "Exposure to second hand smoke",
  "Do you currently use tobacco in any form?",
  'If answered "yes" or "not now", for how many years have you had the habit? ',
  "If not now, how long has it been since you quit the habit? ",
  "Types of tobacco consumption",
  "Frequency of use / day [Smoked tobacco - beedi, cigarettes]",
  "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]",
  "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]",
  "Frequency of use / day [Betel quid without tobacco]",
  "Frequency of use / day [Others ]",
  "Have you attempted to quit tobacco in the past ?",
  "If yes, what was the method you adopted? ",
  "For how many days did you quit the habit? ",
  "What was the reason to quit the habit?",
  "Alcohol consumption status",
  "If yes, since when",
  "If not now, how long has it been since you quit ",
  "For how long did you consume alcohol?",
  "Alcohol consumption frequency",
  "If yes, when? ",
  "Have you undergone any cancer screening tests before?",
  "Which cancer were you screened for?",
  "What was the reason for screening?",
  "Was any blood related family member diagnosed with cancer?",
  "If yes, how many? ",
  "Warning signs of cancer - if any of the following complaints are present / persistent, please tick all the options that apply to you",
  "Female specific symptoms",
  "Menstruation stage",
  "Age of menarche",
  "Last menstrual period",
  "Menstruation",
  "Reason for hysterectomy",
  "Age at hysterectomy",
  "Age at menopause",
  "Gravida",
  "Para",
  "Living",
  "Abortion",
  "Age at first child",
  "1st Child",
  "2nd Child",
  "3rd Child",
  "4th Child",
  "5th Child",
  "6th Child",
  "Hypertension present",
  "K/C/O HTN",
  "Diabetes present",
  "K/C/O DM",
  "Cancer present",
  "K/C/O Cancer",
];
export const mvdNode = ["Heart Rate", "SPO2", "BP/SBP", "BP/DBP", "GRBS", "Total Body Fat", "Subcutaneous Body Fat", "Visceral Body Fat", "Waist Circumference(in cm)", "Hip Circumference(in cm)"];
export const form_3Node = [
  "Screening done for",
  "Findings",
  "Oral cavity Photos",
  "Homogenous leukoplakia",
  "Homogenous leukoplakia - Lesion dimension",
  "Non homogenous leukoplakia",
  "Non homogenous leukoplakia - Lesion dimension",
  "Erythroleukoplakia",
  "Erythroleukoplakia - Lesion dimension",
  "Erythroplakia",
  "Erythroplakia - Lesion dimension",
  "OSMF",
  "Lichen planus present",
  "Lichen planus present - Lesion location",
  "Suspicious ulcer present",
  "Suspicious ulcer present - Lesion size",
  "Suspicious growth",
  "Suspicious growth present - Lesion size",
  "Smokers Palate",
  "Oral punch biopsy indicated",
  "Laser procedure advised",
  "Breast Examination Right breast",
  "Breast Examination Left breast",
  "Abnormality location Right breast",
  "Abnormality location Left breast",
  "Breast Photos",
  "Nipple discharge",
  "Advised bilateral screening mammography",
  "Advised bilateral screening ultrasound",
  "FNAC done when indicated",
  "Nipple discharge smear taken when indicated",
  "Information",
  "Per Speculum",
  "VIA",
  "Releveant images",
  "Pap smear taken",
  "Cervical Punch biopsy indicated",
  "Recommendation",
];
export const tcc_form = [
  "Amount spent on tobacco per day",
  "Types of tobacco consumption",
  "Frequency of use / day [Smoked tobacco - beedi, cigarettes]",
  "Frequency of use / day [Smokeless tobacco - ghutka, hans, pan masala, snuff]",
  "Frequency of use / day [Betel quid with tobacco (kaddipudi, hogesoppu)]",
  "Frequency of use / day [Betel quid without tobacco]",
  "Frequency of use / day [Others ]",
  "For how many years have you had the habit?",
  "Family history of Tobacco use",
  "Family history of Substance use",
  "Family history of Mental disorder use",
  "Age of uptake",
  "Reason for uptake / Starting the habit",
  "I smoke to keep myself alert",
  "Smoking is pleasant and relaxing",
  "I smoke when I am upset about something",
  "I smoke out of boredom",
  "If I run out of cigarette/beedi, I find it unbearable.",
  "I smoke automatically without being aware of it.",
  "I smoke to perk myself up.",
  "I find it difficult to go about my job without smoking",
  "I need to smoke in order to pass motion.",
  "I get real cravings for cigarette/beedi when I haven't used in a while",
  "I use it to keep from slowing down",
  "I like the texture and taste of it in my mouth.",
  "I find it pleasant and relaxing",
  "I use it when I am upset about something",
  "I chew it out of boredom.",
  "If I run out of it, I find it unbearable.",
  "I believe that it provides calcium.",
  "I use it to perk myself up.",
  "It relieves pain in my jaw/teeth.",
  "I find it difficult to go about with my job without it.",
  "Fagerstorm Test for Nicotine Dependence - How soon after you wake up do you smoke your first cigarette?",
  "Fagerstorm Test for Nicotine Dependence - Do you find it difficult to refrain from smoking in places where it is forbidden, e.g., temples, during an outing with family, during village festivities?",
  "Fagerstorm Test for Nicotine Dependence - Which cigarette would you hate most to give up?",
  "Fagerstorm Test for Nicotine Dependence - How many cigarettes per day do you smoke?",
  "Fagerstorm Test for Nicotine Dependence - Do you smoke more frequently during the first hours of waking than during the rest of the day?",
  "Fagerstorm Test for Nicotine Dependence - Do you smoke even if you are sick in bed?",
  "Modified Fagerstorm Test - How soon after you wake up do you place your first dip?",
  "Modified Fagerstorm Test - How often do you intentionally swallow its juice?",
  "Modified Fagerstorm Test - Which chew would you hate most to give up?",
  "Modified Fagerstorm Test - How many cans/pouches per week do you use?",
  "Modified Fagerstorm Test - Do you chew more frequently during the first hours after waking than during the rest of the day?",
  "Modified Fagerstorm Test - Do you chew even if you are sick in the bed?",
  "Do you intend to quit the habit",
  "Have you previously attempted to quit the habit?",
  "what among the following were the barriers to quit?",
  "Do you often forget the intention behind quitting?",
  "Did you have the right social support?",
  "Are you fearful of what might happen if you quit?",
  "Are you anticipating sadness when you quit?",
  "Do you find yourself thinking about death?",
  "Do you wish to live a healthy life?",
  "Do you believe that using tobacco is healthy?",
  "Does anyone in the family believe your habits are unhealthy?",
  "Would you agree if someone told you that use of tobacco in any form is not healthy?",
  "Are you thinking of quitting the habit now?",
  "Do you think that quitting takes a lot of effort?",
  "Do your family support you in quitting the habit?",
  "Do your friends support you in quitting the habit?",
  "Would you be willing to quit if someone from the family puts in the same effort to help?",
  "Would it be helpful if the counsellor gave you a nudge every now and then?",
  "Would you need some time to think whether you want to quit or not?",
  "Do you believe you are capable of quitting?",
  "Do you believe you can quit on your own?",
  "If there were professionals to help you out would you make an effort to quit?",
  "Which form of professional intervention would you prefer ?",
  "Which mode of therapy would you prefer?",
  "Dependency score for smoke tobacco",
  "Dependency level for smoke tobacco",
  "Dependency score for chewing habits",
  "Dependency level for smokeless tobacco",
  "Motivation stage assessed",
  "Counselling Techniques",
];
