export const multiSelectFields = [
  "Exposure to second hand smoke",
  "Types of tobacco consumption",
  "Which cancer were you screened for?",
  "Warning signs of cancer - if any of the following complaints are present / persistent, please tick all the options that apply to you",
  "Female specific symptoms",
  "Screening done for",
  "Findings",
  "Homogenous leukoplakia",
  "Non homogenous leukoplakia",
  "Erythroleukoplakia",
  "Erythroplakia",
  "OSMF",
  "Lichen planus present",
  "Suspicious ulcer present",
  "Suspicious growth",
  "Smokers Palate",
  "Breast Examination Right breast",
  "Breast Examination Left breast",
  "Abnormality location Right breast",
  "Abnormality location Left breast",
  "Nipple discharge",
  "Information",
  "Per Speculum",
  "Types of tobacco consumption ",
  "Reason for uptake / Starting the habit",
  "what among the following were the barriers to quit?",
];
export const rangeSelectFields = ["Age", "Height (in cms)", "Weight (in kgs)", "Age of menarche", "Age at hysterectomy", "Age at menopause", "Gravida", "Age at first child", "Heart Rate", "SPO2"];
export const rangeSelectPlusEnterFields = [
  "Number of family members",
  "Para",
  "Living",
  "Abortion",
  "BP/SBP",
  "BP/DBP",
  "GRBS",
  "Total Body Fat",
  "Subcutaneous Body Fat",
  "Visceral Body Fat",
  "Waist Circumference(in cm)",
  "Hip Circumference(in cm)",
  "Amount spent on tobacco per day",
  "Dependency score for smoke tobacco",
  "Dependency score for chewing habits",
];
